### PR TITLE
feat: adding LogSeq to tools

### PR DESCRIPTION
**Pull request by akosbalasko**

### CODE REVIEW

**Comment by akosbalasko** [comment]
Hi @mattcone ! 
I realized that Logseq is missing from your awesome list of tools in MarkdownGuide, so I added it. However I added the screenshot into the right location (tested locally), I see in Netlify the screenshot is not generated well. Do you have any idea what I'm still missing? 
Thanks, and congrats for Markdownguide, cool stuff!

**Comment by mattcone** [comment]
Thanks for opening this pull request, @akosbalasko! Don't worry about the screenshot — that's due to a misconfiguration mistake on my end. The staging environment thinks it's on production, so it's trying to pull the image from Imgix, the CDN I use for images in production. I'm going to merge this now and will make some minor copyediting changes in a few moments. Thanks again!

**Comment by akosbalasko** [comment]
Oh okay, I get it, thanks for the insights! And thank you for the fast merge too! :) 
If you don't mind, I would add some more tools to the list soon, like Mem or Crafts.do etc. 
Great project!

**Comment by mattcone** [comment]
@akosbalasko: That would be great! Thanks for contributing. And let me know if you have any ideas or suggestions about how to improve things. 😅

**Comment by mattcone** [comment]
I love the idea, but I'm not sure I know enough to design a solution (at least not yet). I know there's general interest in this. In fact, someone made a similar comment on [Hacker News](https://news.ycombinator.com/item?id=16151805):

> It would be great if there was an explainer that simply had comparisons between different flares of MD - e.g Github flavoured. We are working on an open source project with 80k words in MD at the moment an the small syntax stuff is a nightmare. We deal with all kinds of volunteer translators and are always having trouble and mess ups because of it. Having somewhere to point them to would be great!

The [tool directory](https://www.markdownguide.org/tools/) was my first attempt at this, but it's currently too ephemeral and narrow in scope. The closest comparable tool I've found is https://johnmacfarlane.net/babelmark2/ — but it kind of works in reverse. You feed it Markdown and it spits out the HTML from every tool.

Ideally, I'd have to a way to automatically test tools for features. Then yes, as you said, possibly an API or raw data, etc. That should make it easier to compare the features of two tools?

**Pull request merged**
