### PR TITLE
Add page for GitNoter

### PR DESCRIPTION
**Pull request by vivekweb2013**

### CODE REVIEW

**Comment by vivekweb2013** [comment]
@mattcone Could you please review and merge this pr

**Comment by mattcone** [comment]
Hi @vivekweb2013, sorry about the delay. Let me know if you'd like to reopen this.

**Comment by vivekweb2013** [comment]
@mattcone could you please merge the pr. Let me know if something is blocking you from merging

**Comment by mattcone** [comment]
@vivekweb2013: Sorry about the delay. 😅 Have you changed the name of the application to BatNoter?

**Comment by vivekweb2013** [comment]
> @vivekweb2013: Sorry about the delay. 😅 Have you changed the name of the application to BatNoter?

Ohh yes 😄  Because of the trademark issue I had to renamed it recently. Let me create a different pull request with the rename changes. Thanks

**Comment by mattcone** [comment]
Great, no problem. With any luck, I won't take weeks to review the new pull request. 😳

**Pull request closed without merging**
