### PR TITLE
Update NotesHub tool media and description

### PR DESCRIPTION
**Pull request by alex-titarenko**

### CODE REVIEW

**Comment by alex-titarenko** [comment]
@mattcone can you please take a look at this PR, I would really appreciate it!

**Comment by mattcone** [comment]
@alex-titarenko: I restored the previous description as the new one was overflowing on the Tools index page. I also removed the key features section as it sounded too much like an advertisement. Everything else looks good!

**Comment by alex-titarenko** [comment]
@mattcone thank you so much for your review. One thing I noticed was that the screenshot did not get updated on the website, but other changes were deployed. Can you take a look? The new screenshot is very important to me.

**Comment by mattcone** [comment]
@alex-titarenko: I'm sorry — I forgot to purge the cache. My mistake. Please check again. It should be fixed now!

**Comment by alex-titarenko** [comment]
@mattcone thank you very much, it looks good now!!!

**Pull request merged**
