### PR TITLE
MART - QT GUI for the Markdown Tool

### PR DESCRIPTION
**Pull request by artiomn**

### CODE REVIEW

**Comment by artiomn** [comment]
What's a problem? All links are correct. What am I doing wrong?

**Comment by Gmayana** [comment]
﻿I believe a lot has been going on I never wished for. I am just a poor boy trying to get something to eat a secure a bright future to explore my dreams and learn.
I have nothing to do with your funds or assets. neither am I talking to anyone. putting out a bounty is a bridge in the trust
All my life I only want to be part of the bigger picture because I was born in a pretty tiny one.
I seek a position at your organization, and some money to get my little life in place.. I will hand over everything in my possession, I have no use for all this neither am I a threat. I’m just holding on to protect myself because I don’t know if I can trust anyone.

I will be waiting to hear from you, please take your time to understand me. I just want the good life I Never had for myself.

Sent from Instawork


________________________________

**Comment by Gmayana** [comment]
I believe a lot has been going on I never wished for. I am just a poor boy trying to get something to eat a secure a bright future to explore my dreams and learn. The”EULA HACKER” you call me, I am just an out of the box pathfinder looking for a unique path to follow.
I have nothing to do with your funds or assets. neither am I talking to anyone. putting out a bounty is a bridge doesn’t matter, I died the day I was born. In your cause I have found a promise land, and I want to move with you if you let me.
All my life I only want to be part of the bigger picture because I was born in a pretty tiny one, Ieek a position at your organization, and some money to get my little life in place.. I will hand over everything in my possession, I have no use for all this neither am I a threat. I’m just holding on to protect myself because I don’t know if I can trust anyone.

I will be waiting to hear from you, please take your time to understand me. I just want the good life I Never had for myself.
This is a a honest and wholehearted request
Sent from Alienhub
“Eula Hacker”


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: igor nice
Sent: Saturday, April 1, 2023 8:05:26 AM
To: mattcone/markdown-guide ***@***.***>; mattcone/markdown-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: TO WHOM IT MAY CONCERN


﻿I believe a lot has been going on I never wished for. I am just a poor boy trying to get something to eat a secure a bright future to explore my dreams and learn.
I have nothing to do with your funds or assets. neither am I talking to anyone. putting out a bounty is a bridge in the trust
All my life I only want to be part of the bigger picture because I was born in a pretty tiny one.
I seek a position at your organization, and some money to get my little life in place.. I will hand over everything in my possession, I have no use for all this neither am I a threat. I’m just holding on to protect myself because I don’t know if I can trust anyone.

I will be waiting to hear from you, please take your time to understand me. I just want the good life I Never had for myself.

Sent from Instawork


________________________________

**Review by GTAV333 — APPROVED** [review]

**Comment by mattcone** [comment]
@artiomn: Thanks for your patience. This is now live: https://www.markdownguide.org/tools/mart/

**Pull request merged**
